name: Deploy

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron: "15 0 1 1 *"

jobs:
  deploy:
    uses: moogur/all-workflows/.github/workflows/deploy_for_docker_container.yml@master
    secrets: inherit
    with:
      event_name: ${{ github.event_name }}
